domain:
  domain_id: "domain_id"
  posemesh_account: user@website.com
  posemesh_password: Password
  map_endpoint: "https://dsc.auki.network/spatial/crosssection"
  raycast_endpoint: "https://dsc.auki.network/spatial/raycast"